### ISSUE TITLE
Connect to a Wi-Fi SSID of 32 characters (IDFGH-16754)

### ISSUE THREAD

**Issue by mutatrum** [espressif/esp-idf#17838]
### Is your feature request related to a problem?

It's not possible to connect to a SSID with length 32. It is possible to create a Soft AP with SSID 32, as `wifi_ap_config_t` has a `ssid_len`, but `wifi_sta_config_t` does not.

### Describe the solution you'd like.

Add `ssid_len` field to `wifi_sta_config_t`.

**Comment by vik-gokhale** [comment]
hi @mutatrum,
Please specify if this is a connection failure that is being reported via this ticket? If it is, please share information on IDF version used, the logs with WIFI debug and supplicant logging enabled. 

If this is an enhancement request to add 'ssid length' in station config, please note that the application has to issue a connect with just the right SSID and passphrase (without  bothering about ssid length) and the solution connects to the intended network.

**Comment by mutatrum** [comment]
We have a user-facing product, and indeed a ticket open to support 32 character SSID. We have a `char[32]` SSID field, and always put a null-terminator in, which limits it to 31 characters, but maybe that's not needed on a 32 char SSID?

**Comment by vik-gokhale** [comment]
hi @mutatrum,
The SSID field of the Station (Client) config is not a 'char' but a 'uint8_t'.

<img width="482" height="258" alt="Image" src="https://github.com/user-attachments/assets/1da7b124-8ba1-45d0-ad88-4fd4385642a1" />




So in the SoftAP's case, the SSID needs to be null terminated.
But in Station's case, there is no need for a null termination.

**Comment by mutatrum** [comment]
That is a subtlety I completely overlooked. I'll give it a test and report back shortly, thank you!

**Comment by cohelix** [comment]
I would like to point out that the type of SSID is uint8_t for both SoftAP and Station. For SoftAP, the documentation says:

> SSID of soft-AP. If ssid_len field is 0, this must be a Null terminated string. Otherwise, length is set according to ssid_len.

Since wifi_sta_config_t has no ssid_len, it is quite easy to suppose that a null terminator is required based on the previous statement. If that is not the case, it would be great to have that explained in the documentation.

In addition, neither wifi_ap_config_t nor wifi_sta_config_t has a field for the password’s length. Again, this suggests to me that a null terminator is required. Thus, improving documentation would be greatly appreciated. Thank you!

**Comment by mutatrum** [comment]
Fixed the issue on our side. But I agree with @cohelix, the asymmetry between the ssid field in the different config structs is confusing. 

One further point, f.e. `wifi_event_sta_connected_t`, `wifi_event_sta_disconnected_t` and `wifi_event_sta_wps_er_success_t` do have an `ssid_len` field, so it's a mixed bag.

**Comment by ivanpessotto-cyber** [comment]
I want to add that if password is encrypted, it's length is exactly 64 hex digits; so no null-termination can be added, but if the password is plain and it's length is less than 64, a null-termination is needed.
Thats confusing.

I think there must be a standard pattern, either:
- both buffers with one more byte and null-terminated SSID and password (increased respectively to 33 and 65 bytes).
OR
- both buffers NOT null-terminated and a size_t field near to them.

**Comment by julian-weinert** [comment]
Has there been a regression or am I doing something wrong?
I'm trying to assign a 32 character SSID to the `wifi_sta_config_t` struct and am getting a compiler error complaining about a truncated NUL charater.
```c
	#define WIFI_SSID "A1BA4630-A212-4859-85A7-AF4FA9B2C39A"
	wifi_config_t wifi_config = {.sta = {.ssid = WIFI_SSID}};
```
```
error: initializer-string for array of 'unsigned char' truncates NUL terminator but destination lacks 'nonstring' attribute (33 chars into 32 available)
```

**Comment by nachiketkukade** [comment]
@julian-weinert , in your snippet the `WIFI_SSID` length is of 36 including the hyphens. Can you confirm if you use it without the hyphens in your application?
Assuming you used any string assignment, it's still not a regression. It's a GCC 15 warning (-Wunterminated-string-initialization), which appears after v5.5 -> v6.0 migration. See the migration guide point mentioned here - https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/release-6.x/6.0/toolchain.html#wno-unterminated-string-initialization.
Instead of suppressing it, suggestion is to use the 32 octets with memcpy (do not rely on a terminator).

**Comment by nachiketkukade** [comment]
@ivanpessotto-cyber  The 8–63 vs 64-hex split is the IEEE 802.11 PSK config (8–63 passphrase vs 64 hex digits), not an ESP implementation quirk.
password[64] is either an 8–63 character passphrase (NUL-terminated in the buffer) or exactly 64 hex digits of a raw PSK (fills the array; no extra NUL). Hex digits are the 256-bit PSK written as hex, not exactly an “encrypted password”.

We'll add a better doc for wifi_sta_config_t / api-guide so that the same confusion doesn't keep occurring. Closing this thread since OP queries were resolved
