### ISSUE TITLE
[ESP32-P4] CONFIG_ESP_REV_MIN_FULL is empty in bootloader builds on master branch (IDFGH-16925)

### ISSUE THREAD

**Issue by niver2002** [espressif/esp-idf#17986]
## Answers checklist.
- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [x] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [x] I have searched the issue tracker for a similar issue and not found a similar issue.

## IDF version.
v6.1-dev-1054-g487551888a (master branch)

## Espressif SoC revision.
ESP32-P4

## Operating System used.
Windows

## How did you build your project?
VS Code IDE

## If you are using Windows, please specify command line type.
PowerShell

## What is the expected behavior?
\CONFIG_ESP_REV_MIN_FULL\ should have a valid numeric value (e.g., \

**Comment by niver2002** [comment]
﻿## Updated Workaround (Tested & Working)

The previous suggested Kconfig fix alone is not sufficient. A more complete workaround is needed.

### Working Solution

Add the following fallback in `components/hal/platform_port/include/hal/config.h`, right after `#include "sdkconfig.h"`:

```c
// Fallback for empty CONFIG_ESP_REV_MIN_FULL (ESP-IDF master bug in bootloader)
#if !defined(CONFIG_ESP_REV_MIN_FULL) || (CONFIG_ESP_REV_MIN_FULL + 0 == 0 && !defined(CONFIG_ESP32P4_REV_MIN_0))
#undef CONFIG_ESP_REV_MIN_FULL
#define CONFIG_ESP_REV_MIN_FULL 0
#endif
```

### Important Notes for ESP32-P4 Rev <3.0 users:

Make sure your `sdkconfig.defaults` includes:
```
CONFIG_ESP32P4_SELECTS_REV_LESS_V3=y
```

This ensures the firmware is built for chip revisions v0.x-v1.99 instead of v3.0+.

Without this setting, even if compilation succeeds, esptool will refuse to flash with:
```
'bootloader/bootloader.bin' requires chip revision in range [v3.0 - v3.99] (this chip is revision v1.3)
```

### Test Result
- ESP32-P4 Rev v1.3
- ESP-IDF master v6.1-dev
- Build: Success
- Flash: Success

**Comment by fhrbata** [comment]
Hello @niver2002 , 

thank you for the report. I believe this issue should be already addressed by https://github.com/espressif/esp-idf-kconfig/commit/82a03d9ebaa64de887e20626e22a3736e9cc1597 in the esp-idf-kconfig. Maybe you can give it a try to see if it fixes the problem for you.

Within the activated esp-idf python venv: `pip install git+https://github.com/espressif/esp-idf-kconfig.git`

Thank you

**Comment by niver2002** [comment]
The fix (commit espressif/esp-idf-kconfig@82a03d9) has been merged to `esp-idf-kconfig` master on Dec 4, but **it has not been released to PyPI yet**. The latest PyPI version is still 3.3.0 (released Nov 4, 2025).

Since ESP-IDF's `requirements.core.txt` installs `esp-idf-kconfig` from PyPI without pinning to a specific commit, users installing ESP-IDF master today still get the old buggy version.

**Request:** When pushing updates to ESP-IDF master that depend on fixes in companion tools (esp-idf-kconfig, esptool, etc.), please also publish new versions of those tools to PyPI. Otherwise, the fixes are effectively unavailable to users who install through normal channels (VSCode ESP-IDF extension, `install.bat`, etc.).

Workaround for now:
```
pip install git+https://github.com/espressif/esp-idf-kconfig.git@master
```

**Comment by dobairoland** [comment]
A new version of esp-idf-kconfig is released today.

Everyone can get the fix after re-running the install scripts.
